name: Discord Reminder

on:
  schedule:
    - cron: '0 */12 * * 6,0'
  workflow_dispatch:

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord webhook reminder
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\":\"🔔 **Reminder / Напоминание**\n\nPlease remember to **complete sect construction** and **donate Otherworld transfer tokens**.\nПожалуйста, не забудьте **завершить строительство секты** и **пожертвовать токены переноса из Иного мира**.\n\n📘 Instructions for both are posted in <#1373189131512840243> (FAQ channel).\n📘 Инструкции по обоим действиям находятся в <#1373189131512840243> (канал FAQ).\"}" \
          "$WEBHOOK_URL"
